1.: What does NumPy stand for? 

Ans :- Numerical Python 

2.: Which of the following is the correct way to import NumPy?

Ans :-  import numpy as np 

3.: Which data structure is used in NumPy to represent n-dimensional arrays?

Ans :- ndarray

In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a.shape)
print(a.ndim)

(5,)
1


4.: How to create an array of zeros with shape (3, 4) in NumPy? 

Ans :- np.zeros((3, 4))

In [11]:
b = np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


5.: What does the function np.arange(5, 15, 2) return?

Ans :- [5, 7, 9, 11, 13]

In [12]:
c =np.arange(5,15,2)
print(c)

[ 5  7  9 11 13]


6.: How to perform element-wise multiplication of two arrays in NumPy?

Ans :- np.multiply(arr1, arr2)

In [15]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = a * b
print(c)

# d = a.multiply(b)
# print(d)

e = np.multiply(a,b)
print(e)

[ 5 12 21 32]
[ 5 12 21 32]


7.: What does the function np.linalg.inv(matrix) do in NumPy?

Ans :- Calculates the inverse of the matrix

In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.linalg.inv(a)
print(b)

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


8.: How can you stack two arrays vertically in NumPy? 

Ans :- np.vstack((arr1, arr2)) 

In [22]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.vstack((a,b))
print(c)

# d = np.concatenate((a,b),axis=0)
# print(d)

# e = np.append(a,b,axis=0)
# print(e)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


9.: How to find the maximum value along a specific axis in a NumPy array?

Ans :- np.max(array, axis=0)

In [38]:
# a = np.array([1,2,3,4])
# m = np.max(a,axis=0)
# print(m)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.max(b,axis=0)
print(b)


[7 8 9]


10.MCQ: Which NumPy function is used to generate random numbers from a uniform distribution over the interval [0, 1)? 

Ans :- All of the above

In [42]:
a = np.random.random()
print(a)

b = np.random.uniform()
print(b)

c = np.random.rand()
print(c)

0.8869686747279933
0.9418620939232923
0.5745415627674548


11. : Consider two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). What is the result of the following
      operation: np.dot(arr1, arr2)?

Ans :- 32

In [43]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

a = np.dot(arr1,arr2) #The np.dot() function in NumPy is used to compute the dot product of two arrays.
print(a)              # 2-dimensional (matrices), it performs matrix multiplication.

32


12.: Given a NumPy array arr = np.array([10, 20, 30, 40, 50]), what is the result of np.gradient(arr)? 

Ans :- [10, 10, 10, 10, 10]  

In [44]:
arr = np.array([10, 20, 30, 40, 50])  #The np.gradient() function in NumPy is used to compute the gradient of an array. 
                                #The gradient represents the rate of change of values in the array along different dimensions.
a = np.gradient(arr)
print(a)

[10. 10. 10. 10. 10.]


13.: What does the NumPy function np.where(arr > 5, 1, 0) do?

Ans :- Sets elements greater than 5 to 1 and others to 0. 

In [45]:
arr1 = np.array([1,3,9,6,8,4,7,2])
a = np.where(arr1>5,1,0)
print(a)

[0 0 1 1 1 0 1 0]


14.: Consider a 2D NumPy array arr = np.array([[1, 2], [3, 4]]). What is the result of np.trace(arr)?

Ans :- 5

In [46]:
arr = np.array([[1, 2], [3, 4]]) #The np.trace() function in NumPy is used to compute the sum of the diagonal elements of a 
a = np.trace(arr)                 # matrix.
print(a)

5


15.: Given two NumPy arrays arr1 = np.array([1, 2, 3, 4]) and arr2 = np.array([3, 4, 5, 6]), how can you find the elements that are common between both arrays?

Ans :- np.intersect1d(arr1, arr2) 

In [47]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

c = np.intersect1d(arr1,arr2)
print(c)


[3 4]


16.: How can you concatenate two 2D NumPy arrays arr1 and arr2 vertically (row-wise)?

Ans :- All of the above.

In [53]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

a = np.concatenate((arr1,arr2))
print(a)

b = np.row_stack((arr1,arr2))
print(b)

c = np.vstack((arr1,arr2))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


17.: Given a 1D NumPy array arr = np.array([10, 20, 30, 40, 50]), what is the result of arr[1:4]?

Ans :- [20 30 40]

In [54]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


18.: How can you calculate the mean value of a 2D NumPy array arr along the columns (axis=0)?

In [ ]:
Ans :- np.mean(arr, axis=0) 

In [59]:
arr1 = np.array([[1,2],[3,4]])
m = np.mean(arr1,axis=0)
print(m)

[2. 3.]


19.: Which NumPy function is used to calculate the cumulative sum of elements in an array? 

In [ ]:
Ans :- np.cumsum() 

In [60]:
arr1 = np.array([1, 2, 3, 4])
s = np.cumsum(arr1)
print(s)

[ 1  3  6 10]


20.: Given a 2D NumPy array arr, how can you sort the rows based on the values in the second column?

Ans :- arr[arr[:, 1].argsort()]

In [79]:
arr1 = np.array([[2,5,4],[3,4,1],[6,2,7]])
# a = np.sort(arr1)
# print(a)

sort = np.argsort(arr1[:,1])
print(sort)

sort_v = arr1[sort]
print(sort_v)

[2 1 0]
[[6 2 7]
 [3 4 1]
 [2 5 4]]


21.: Which NumPy function is used to calculate the element-wise exponential of an array? 

Ans :- np.exp()

In [80]:
arr1 = np.array([1, 2, 3, 4])
e = np.exp(arr1)
print(e)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


22.: Given a 1D NumPy array arr = np.array([3, 1, 4, 2, 5]), what is the result of np.argsort(arr)?

Ans :- [1, 3, 0, 2, 4] 

In [82]:
arr = np.array([3, 1, 4, 2, 5]) #The np.argsort() function in NumPy returns the indices that would sort an array along a 
a = np.argsort(arr)             #specified axis.
print(a)
b = arr[a]
print(b)

[1 3 0 2 4]
[1 2 3 4 5]


23.: How can you calculate the cross product of two 1D NumPy arrays arr1 and arr2?

Ans :- np.cross(arr1, arr2)

In [83]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

a = np.cross(arr1,arr2)
print(a)

[-3  6 -3]


24.: Given a 2D NumPy array arr, how can you find the unique rows in the array? 

Ans :- np.unique(arr, axis=0) 

In [88]:
arr1 = np.array([[2,5,4],[3,4,1],[2,5,4],[6,2,7]])
u = np.unique(arr1,axis=0)
print(u)



[[2 5 4]
 [3 4 1]
 [6 2 7]]


25.: What is the result of np.random.randint(1, 10, size=(3, 3))? 

Ans :- A 3x3 array with random integers between 1 and 10.

In [90]:
a = np.random.randint(1,10,size=(3,3))
print(a)

[[6 8 7]
 [5 3 9]
 [4 4 1]]


26.: How can you calculate the element-wise square root of a NumPy array arr?

Ans :- np.sqrt(arr)

In [91]:
arr = np.array([3, 1, 4, 2, 5]) 
s = np.sqrt(arr)
print(s)

[1.73205081 1.         2.         1.41421356 2.23606798]


27.: Given a 1D NumPy array arr, how can you find the indices of elements that are non-zero? 

Ans :- All of the above

In [94]:
arr = np.array([3, 1, 0, 2, 5,0,4]) 
z = np.nonzero(arr)     # show indices of non-zero 
print(z)

z1 = np.where(arr!=0)
print(z1)

z3 = arr.nonzero()
print(z3)

(array([0, 1, 3, 4, 6], dtype=int64),)
(array([0, 1, 3, 4, 6], dtype=int64),)
(array([0, 1, 3, 4, 6], dtype=int64),)


28.MCQ: How can you calculate the element-wise absolute value of a NumPy array arr?

In [ ]:
Ans :- np.abs(arr)

In [98]:
arr = np.array([-3, 1, 4, -2, 5]) 
a = np.abs(arr)
print(a)



[3 1 4 2 5]


29.MCQ: What does the NumPy function np.bincount(arr) do? 

Ans :- Computes the number of occurrences of each unique element in the array.

In [100]:
arr = np.array([3,1,3,4,0,2,5,0,4]) 
u = np.bincount(arr)
print(u)

[2 1 1 2 2 1]


30.: Given a 2D NumPy array arr, how can you get the second column as a separate array?

Ans :- arr[:, 1] 

In [106]:
arr1 = np.array([[2,5,4],
                 [3,4,1],
                 [2,5,4],
                 [6,2,7]])
print(arr1[:,1])

[5 4 5 2]


31.MCQ: What is the result of the following code?arr = np.array([10, 20, 30, 40, 50])result = arr[arr > 25]

Ans :- [30, 40, 50]

In [107]:
arr = np.array([10, 20, 30, 40, 50])
result = arr[arr > 25]
print(result)

[30 40 50]


32.MCQ: How can you create a 2D identity matrix with size 5x5 using NumPy?

Ans :- np.eye(5)

In [108]:
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


33.MCQ: Given two 2D NumPy arrays arr1 and arr2, how can you calculate the element-wise minimum of both arrays?

Ans :- np.minimum(arr1, arr2) 

In [117]:
arr1 = np.array([[1,4],
                 [9,10]])
arr2 = np.array([[4,3],
                 [7,8]])

m = np.minimum(arr1,arr2)
print(m)

[[1 3]
 [7 8]]


34.MCQ: What is the result of the following code? arr = np.array([1, 2, 3])arr = arr.reshape(-1, 1)

Ans :- [[1], [2], [3]]

In [118]:
arr = np.array([1, 2, 3])
arr1 = arr.reshape(-1, 1)
print(arr1)

[[1]
 [2]
 [3]]


35.MCQ: How can you calculate the element-wise exponentiation of a NumPy array arr with a specific base (e.g., 2)?

Ans :- np.power(arr, 2) 

In [122]:
arr = np.array([1, 2, 3])
e = np.power(arr,2)
print(e)

[1 4 9]


36.MCQ: Given a 2D NumPy array arr, how can you find the index of the maximum value in the array? 

Ans :- np.argmax(arr)

In [125]:
arr1 = np.array([[2,5,4],
                 [3,4,1],
                 [2,5,4],
                 [6,2,7]])
m = np.argmax(arr1)
print(m)


11


37.MCQ: What does the NumPy function np.meshgrid(arr1, arr2) do?

Ans :-  Creates a grid of points based on two coordinate vectors

In [126]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

m = np.meshgrid(arr1,arr2) #The np.meshgrid() function in NumPy is used to create a grid of coordinates from one or more 1D 
print(m)                  #arrays.

[array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]), array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])]


38.MCQ: How can you flatten a 2D NumPy array arr into a 1D array?

Ans :- arr.flatten()

In [128]:
arr1 = np.array([[2,5,4],
                 [3,4,1],
                 [2,5,4],
                 [6,2,7]])

f = arr1.flatten()
print(f)

[2 5 4 3 4 1 2 5 4 6 2 7]


39.MCQ: Given a 1D NumPy array arr, how can you replace all odd values with -1?

Ans :- arr[arr % 2 != 0] = -1 

In [134]:
a = np.array([2,5,4,3,4,1,2,5,4,6,2,7])
a[a%2!=0]=-1
print(a)


[ 2 -1  4 -1  4 -1  2 -1  4  6  2 -1]


40.MCQ: How can you calculate the covariance matrix of a 2D NumPy array arr?

In [ ]:
Ans :- np.cov(arr) 

In [137]:
arr1 = np.array([[2,5,4],
                 [3,4,1],
                 [2,5,4],
                 [6,2,7]])
c = np.cov(arr1)          #The np.cov() function in NumPy is used to compute the covariance matrix of a given array. 
                    #The covariance matrix provides insights into the linear relationship between variables in the array.
print(c)


[[ 2.33333333  0.33333333  2.33333333 -2.5       ]
 [ 0.33333333  2.33333333  0.33333333 -3.5       ]
 [ 2.33333333  0.33333333  2.33333333 -2.5       ]
 [-2.5        -3.5        -2.5         7.        ]]
